### ISSUE TITLE
想选取某几列导出，有参数可以传吗？

### ISSUE THREAD

**Issue by 553082694** [neil3d/excel2json#11]
比如想选取第一列，第三列，排除第二列，需要怎么做呢？
因为同一张表，策划在配置的时候，有些字段是服务器端用到的，有些字段是客户端用到的。不需要用到的字段，不希望生成到文件中去。这个需求要怎么实现？

**Comment by neil3d** [comment]
准备加一个命令行参数：column_name:value，就是“列的值”为指定值的行才会导出

**Comment by neil3d** [comment]
Ver 1.4.0 新加了可以排除掉指定前缀的列的功能：https://github.com/neil3d/excel2json/releases/tag/v1.4.0
- 你可以给表格的列加上：类似 client_ 和 server_  这种前缀
- 导出给客户端用的数据时使用命令行开关： -exclude_prefix server_
- 导出给服务端用的数据时使用命令行开关： -exclude_prefix client_
