### ISSUE TITLE
excel表内填的日期会有问题

### ISSUE THREAD

**Issue by yksalun** [neil3d/excel2json#12]
比如有列数据：
Date_Begin
开启日期
2018/06/05

那么这个日期在object value = row[column];读出来的时候就变成了{2018/6/5 0:00:00}
我不想要后面的时间，我只想要日期，请问要怎么处理呢？

**Comment by neil3d** [comment]
1.2版本会增加一个参数，用来控制时间日期的生成，通过命令行参数 date 或者 GUI 填入参数：“dd/MM/yyy” 即可
