### ISSUE TITLE
导出类型为json对象数组该如何配置表呢?

### ISSUE THREAD

**Issue by fattigerlee** [neil3d/excel2json#13]

**Comment by huskarlee** [comment]
比如json结构为:
{
	"Test":[
		{"ID":"111:","Name":"111"},
		{"ID":"222:","Name":"222"},
		{"ID":"333:","Name":"333"}
	]
}

**Comment by neil3d** [comment]
Excel 表不需要特殊配置，按照例子中的表格3行表头即可。
在导出时：如果是命令行模式，则使用 -array 参数；如果是GUI模式，则把 export type 选择为 array 即可。
