### ISSUE TITLE
如果有双索引就更美了

### ISSUE THREAD

**Issue by cbscea** [neil3d/excel2json#15]
例如表格是
ids typs name
1      1      111
2      1      222
3      2      333
4      2     444
转成json:
第一种
1{
  1{
     name:111
    },
 2{
    name:222
 }
}
或者
1_1{
name:111
 },
1_2:
{
 name ：222
}
这样就更爽了。。有的表需要双重定位。。需求还蛮多的。。

**Comment by neil3d** [comment]
恩，Unreal4导入的JSON就需要这种格式，近期会加上

**Comment by neil3d** [comment]
仔细看了一下，你说的格式比较特殊，我就没添加了。
1.2版本添加了虚幻4对应的格式。
