### ISSUE TITLE
感谢作者的软件，能不能设置不导出某个Sheet？

### ISSUE THREAD

**Issue by lailongmen** [neil3d/excel2json#16]
有个别的导出软件，就是命名!开头的Sheet，不导出。

**Comment by neil3d** [comment]
这个需求应该是比较常见的，不过，不想添加这种隐式规则来实现，否则后面会乱。

**Comment by neil3d** [comment]
Ver 1.4.0 新加了这个功能：https://github.com/neil3d/excel2json/releases/tag/v1.4.0
