### ISSUE TITLE
导出Json字典时有冗余字段,帮忙修改下

### ISSUE THREAD

**Issue by daroubing** [neil3d/excel2json#17]
你好,工具非常好用.不过导出Json字典时有冗余字段,帮忙修改下
![image](https://user-images.githubusercontent.com/22874210/58565717-c4667b80-8261-11e9-8f01-988771a88483.png)

**Comment by exe19890522** [comment]
编辑excel的时候不要把焦点单元格点在你不需要的列里面，直接把鼠标点在A1单元格就行了。然后再排除E列里面的单元格没有什么东西，比如要是多出来123，就意味着是EFG三列都有你看上去没有实际却有的东西在，你可以选中那几列然后删除列就行了。

**Comment by sunzhengjun** [comment]
确实有多余的字段产生，上面的方法试了不行

**Comment by AfarMiss** [comment]
最新版同样的问题,会产生多余的"ID" : "ID"

**Comment by exe19890522** [comment]
那我就不清楚了，你最好是事先准备的是空白表，然后在别的表里面弄好数据，再选中你想要的内容复制粘贴到空白表里面吧。

**Comment by zjglwt** [comment]
同样遇到了这个问题，导出成字典会产生莫名其妙的"ID":"ID"字段。

**Comment by dantezhu** [comment]
@daroubing 已解决，拉一下最新master代码。

**Comment by neil3d** [comment]
版本  v1.2.1 已经解决 感谢 @dantezhu  提供 PR
