### ISSUE TITLE
作者，这个东西到底怎么用，你写的操作指南对于新手来说并不友好，能不能，写个清楚点的操作指南

### ISSUE THREAD

**Issue by liudan420** [neil3d/excel2json#20]

**Comment by exe19890522** [comment]
> _No description provided._

这个东西不是很简单的啊，很容易上手的啊？excel里面前三行注意一下就行了。
第一行是可以引用的字段比如id、name、value，第二行是字段的类型比如string、int，
第三行是你对字段的备注，看看用的，实际不会打包到json里面的。
然后把excel文件拖到工具界面上，然后点一下保存json就行了。

**Comment by exe19890522** [comment]
> _No description provided._

选项options下面的选择一般是array，utf8-nobom，no，3。
这里的3就是之前在excel里面的前三行（不是数据）的意思，你如果改成2，那么之前的备注一行要删掉。

**Comment by liudan420** [comment]
谢谢解释，我有点笨，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "haoyu"<notifications@github.com&gt;; 
发送时间: 2019年11月19日(星期二) 上午10:16
收件人: "neil3d/excel2json"<excel2json@noreply.github.com&gt;; 
抄送: "蛋蛋呀"<liudang1993@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neil3d/excel2json] 作者，这个东西到底怎么用，你写的操作指南对于新手来说并不友好，能不能，写个清楚点的操作指南 (#20)



 
No description provided.
  
这个东西不是很简单的啊，很容易上手的啊？excel里面前三行注意一下就行了。
 第一行是可以引用的字段比如id、name、value，第二行是字段的类型比如string、int，
 第三行是你对字段的备注，看看用的，实际不会打包到json里面的。
 然后把excel文件拖到工具界面上，然后点一下保存json就行了。
