### ISSUE TITLE
请问数据能导出数组格式吗？

### ISSUE THREAD

**Issue by hjx503838528** [neil3d/excel2json#21]
目前只能导出 int，data，string。。 但我[1,2,3]数组导出的时候就变字符串了

**Comment by neil3d** [comment]
版本1.4.1加了一个新功能：自动识别和转换单元格内的 Json String，不但可以支持转换数组，还可以转换Json对象，
详见项目README，版本已经发布：https://github.com/neil3d/excel2json/releases/tag/v1.4.1
