### ISSUE TITLE
谢谢作者。请问怎么打开GUI模式呀，我下载的包没有exe文件

### ISSUE THREAD

**Issue by Skcai2028** [neil3d/excel2json#22]
不好意思，我是新手程序猿，新手git使用者

**Comment by cropsz** [comment]
下载ZIP格式的文件，解压后里面有可执行文件
直接下载：[excel2json_120.zip
](https://github.com/neil3d/excel2json/releases/download/v1.2.0/excel2json_120.zip)
最新版下载：[https://github.com/neil3d/excel2json/releases](https://github.com/neil3d/excel2json/releases)

**Comment by Skcai2028** [comment]
谢谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cropsz <notifications@github.com&gt;
发送时间: 2020年4月25日 17:39
收件人: neil3d/excel2json <excel2json@noreply.github.com&gt;
抄送: Skcai2028 <88968236@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neil3d/excel2json] 谢谢作者。请问怎么打开GUI模式呀，我下载的包没有exe文件 (#22)





 
下载ZIP格式的文件，解压后里面有可执行文件
 直接下载：excel2json_120.zip
 
 最新版下载：https://github.com/neil3d/excel2json/releases
