### ISSUE TITLE
1.1.1和1.1.0源码检测有特洛伊

### ISSUE THREAD

**Issue by smileOcean11** [neil3d/excel2json#23]
1.1.1和1.1.0源码检测有特洛伊

**Comment by exe19890522** [comment]
> 1.1.1和1.1.0源码检测有特洛伊

360卸载掉吧，我金山卫士没报警。你不相信的话，自己上传到国际病毒查杀网页去扫描吧

**Comment by neil3d** [comment]
> 1.1.1和1.1.0源码检测有特洛伊

源代码就在那里，请自己Review吧
