### ISSUE TITLE
能否恢复生成C#结构的功能

### ISSUE THREAD

**Issue by cn914287516** [neil3d/excel2json#25]
最新版去掉了这个功能

**Comment by cn914287516** [comment]
谢谢

**Comment by neil3d** [comment]
版本 1.3.0 把这个功能加回来了，请更新：https://github.com/neil3d/excel2json/releases/tag/v1.3.0

**Comment by cn914287516** [comment]
> 版本 1.3.0 把这个功能加回来了，请更新：https://github.com/neil3d/excel2json/releases/tag/v1.3.0

感谢感谢！
