### ISSUE TITLE
数组类型能否不转成string类型

### ISSUE THREAD

**Issue by laji963852741** [neil3d/excel2json#28]
转化结果
{
{
"id":1,
"tags":"[\"player\",\"enemy\"]"
}
}
希望结果
{
{
"id":1,
"tags":["player","enemy"]
}
}

**Comment by neil3d** [comment]
Excel 的单元格貌似没有 “数组” 这种类型吧？ 如果有的话，可以尝试识别

**Comment by exe19890522** [comment]
> 转化结果
> {
> {
> "id":1,
> "tags":"["player","enemy"]"
> }
> }
> 希望结果
> {
> {
> "id":1,
> "tags":["player","enemy"]
> }
> }

excel转换成json之后的内容都是string格式的，不存在[]数组类型的，不能直接读取的，你只能使用分隔符的形式保存数组
比如“1|2|3”指代[1,2,3]这样的数组。他也很方便就能在js中还原成数组

**Comment by neil3d** [comment]
一咬牙一跺脚，加了一个新功能：自动识别和转换单元格内的 Json String，不但可以支持转换数组，还可以转换Json对象，
详见项目README，版本已经发布：https://github.com/neil3d/excel2json/releases/tag/v1.4.1
