### ISSUE TITLE
哪位能否更新一下新版Release binary文件，手边只有mac 用mono跑，没有windows环境.

### ISSUE THREAD

**Issue by inkcomic** [neil3d/excel2json#30]
看到修了一个导出的json数据带有错误项的bug，能否请可以编译的同学更新一下binary？

**Comment by neil3d** [comment]
新版本已经发布：https://github.com/neil3d/excel2json/releases/tag/v1.2.1

**Comment by inkcomic** [comment]
> 新版本已经发布：https://github.com/neil3d/excel2json/releases/tag/v1.2.1

感谢!
