### ISSUE TITLE
可以添加忽略规则来忽略某些不想要参与转换的（例如在列首名字前面加上字符“#”来忽略这一列）行或列吗？

### ISSUE THREAD

**Issue by Nomoax** [neil3d/excel2json#31]

**Comment by neil3d** [comment]
这个需求记下了；
不过，不想添加这种隐式规则来实现，否则后面会乱。

**Comment by zyowo** [comment]
有时候需要给策划看 某个ID 对应的名字，用表格跳转的，但程序不需要导出
UnityCSV 的那个库是用了 # 的规则

**Comment by neil3d** [comment]
Ver 1.4.0 添加了可以知道前缀来排除表单或者列的功能：https://github.com/neil3d/excel2json/releases/tag/v1.4.0
