### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by S1ow** [neil3d/excel2json#33]
![image](https://user-images.githubusercontent.com/13724705/93731030-e07ff000-fbfd-11ea-824b-2060d2ab824d.png)

**Comment by neil3d** [comment]
不带参数会默认启动 GUI 模式，在 Mac 下不支持；
你可以加上参数，应该是可以执行的，具体请看：https://neil3d.gitee.io/coding/excel2json.html
另外，正在准备使用 .Net Core 重构这个项目，到时候对 Mac 的支持会更好一些。
