### ISSUE TITLE
当xlsx在excel中打开时无法转表

### ISSUE THREAD

**Issue by Luna1996** [neil3d/excel2json#34]

**Comment by isengardd** [comment]
ExcelLoader函数里的这行代码修改一下，重新编译。
`
            using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)) {
`
选择flieShare方式为ReadWrite。

**Comment by neil3d** [comment]
> ExcelLoader函数里的这行代码修改一下，重新编译。
> `using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)) {`
> 选择flieShare方式为ReadWrite。

多谢，回头我会修正到版本中。

**Comment by neil3d** [comment]
版本1.4.2已经修改
