### ISSUE TITLE
标准化json格式数据生成

### ISSUE THREAD

**Issue by icefire0102** [neil3d/excel2json#37]
能否增加一个功能，生成图片中的标准化json格式呢
![image](https://user-images.githubusercontent.com/42762744/100495566-c88d9500-3187-11eb-8aa9-a943e39c25f6.png)

**Comment by neil3d** [comment]
呃。。。这个工具只是转换 excel。。。。
而，实际好，这种数据的生成，在 MS Excel 软件中是很方便操作的
