### ISSUE TITLE
序列化结果问题

### ISSUE THREAD

**Issue by macrobin** [neil3d/excel2json#4]
以下是序列化的结果
{
  "1": {
    "id": 1,
    "name": "Apple_G",
    "scrores": 3
  },
  "2": {
    "id": 2,
    "name": "Apple_R",
    "scrores": 4
  }
}
以下是想要序列化的结果
[
  {
    "id": 1.0,
    "name": "Apple_G",
    "scrores": 3.0
  },
  {
    "id": 2.0,
    "name": "Apple_R",
    "scrores": 4.0
  }
]

**Comment by macrobin** [comment]
以下想要的结果
[
  {
    "id": 1.0,
    "name": "Apple_G",
    "prefab": "Apple_G",
    "scrores": 3.0
  },
  {
    "id": 2.0,
    "name": "Apple_R",
    "prefab": "Apple_R",
    "scrores": 4.0
  }
]

**Comment by neil3d** [comment]
这个功能很有必要，已经添加到master。通过命令行参数"--array"来控制，例如：
excel2json --excel test.xlsx --json test.json --header 3 **--array true**
你可以试试。：）
