### ISSUE TITLE
工具非常好用，但是相同数据不能折叠

### ISSUE THREAD

**Issue by xiaogaoqi** [neil3d/excel2json#42]
比如：表中配置多个，相同关卡数据，相同关卡下面有不同的小关卡，不能见这些小关卡折叠同一个大关卡下

**Comment by xiaogaoqi** [comment]
![image](https://user-images.githubusercontent.com/26711840/115984271-c0bc0a80-a5d8-11eb-8169-1ea83b807e33.png)
![image](https://user-images.githubusercontent.com/26711840/115984296-e812d780-a5d8-11eb-9b35-bc1594a9afa0.png)
现在是进行的每一行读取，有的时候需要相同数据进行折叠

**Comment by neil3d** [comment]
暂时没有计划支持这种功能。：）
