### ISSUE TITLE
多个sheet

### ISSUE THREAD

**Issue by andygithubchen** [neil3d/excel2json#6]
不支持多个sheet???

**Comment by neil3d** [comment]
目前不支持多个sheet。可以说说你的需求，每个sheet分别导出吗？

**Comment by dyc92** [comment]
我设想的支持多sheet是: 配置允许多sheet合并在一个json中,以sheet name作json key

**Comment by andygithubchen** [comment]
对，和@dyc92一样的需求

**Comment by dengxuhui** [comment]
多sheet需要就该panelExcelDropBox_DragDrop函数逻辑对么，对应dropData是不是页签集合呢，现在程序没跑起来，只在研究源代码。

**Comment by neil3d** [comment]
这个需求我自己也遇到了，这几天会加上

**Comment by neil3d** [comment]
1.2版本已经添加：
默认导出表中所有Sheet，格式为：{ SheetName: { SheetOBject } }
