### ISSUE TITLE
mac下使用命令行编译有问题

### ISSUE THREAD

**Issue by OpenYourEye** [neil3d/excel2json#7]
mono ./excel2json.exe --excel test.xlsx --json test.json --header 3 --array true

报错:Error: Object reference not set to an instance of an object

**Comment by neil3d** [comment]
你是用的最新版吗？我印象中 v 1.1.1 已经修复了这个问题了

**Comment by OpenYourEye** [comment]
找到问题了~是因为我在mac上建的excel~从win那边拿过来的就是正常的
