### ISSUE TITLE
mac 下用mono命令行调用，生成多余的空数据

### ISSUE THREAD

**Issue by dyc92** [neil3d/excel2json#8]
`    "id": 10001,
    "name": "手枪",
    "weaponType": "pistol",
    "system": "reality",
    "icon": "",
    "ATT": 1,
    "attackSpeed": 1,
    "attackRange": "直线",
    "distance": 1000,
    "clip": 15,
    "recoil": 0,
    "Column11": "",
    "Column12": "",
    "Column13": "",
    "Column14": "",
    "Column15": "",
    "Column16": "",
    "Column17": "",
    "Column18": "",
    "Column19": "",
    "Column20": "",
    "Column21": "",
    "Column22": "",
    "Column23": "",
    "Column24": "",
    "Column25": "",
    "Column26": "",
    "Column27": ""`
查看了下是Excel库读sheet取到了200多行，27列，
<img width="925" alt="d900e817-0fde-40a5-8dce-cdd57dfb6bbb" src="https://user-images.githubusercontent.com/12205284/35675770-44437286-0784-11e8-95b9-0e856c05df31.png">

**Comment by dyc92** [comment]
windows下也是有的

**Comment by neil3d** [comment]
Excel表格中那些行和列是不是也是有的？内容为空？你删除一些空行、列试试

**Comment by dyc92** [comment]
试过了，应该是引用的库的原因，加了判断type不存在就跳过此行，我扩展了多sheet的读取和跳过，值验证和报错提示和大数的读取，你应该用dotnet core重写，顺应时代嘛！

**Comment by dyc92** [comment]
再增加转换成csv，去掉转成sql

**Comment by neil3d** [comment]
sql 已经去掉，csv再看看
